<?php

namespace App\Services\Unselected\Providers;

use App\Service\Unselected\Unselected;
use App\Services\Unselected\UnselectedService;
use Illuminate\Support\ServiceProvider;

class UnselectedProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(Unselected::class,UnselectedService::class);
        parent::register(); // TODO: Change the autogenerated stub
    }
}
